<?php
/**
 * Plan catalog service.
 *
 * @package WP_Ultimo
 * @subpackage Services
 * @since 2.5.0
 */

namespace WP_Ultimo\Services;

use WP_Ultimo\Database\Products\Product_Type;
use WP_Ultimo\Models\Product;
use WP_Ultimo\Models\Signup_Service;
use WP_Ultimo\Traits\Singleton;

// Exit if accessed directly
defined('ABSPATH') || exit;

/**
 * Service responsible for resolving and normalizing plan product data.
 *
 * @since 2.5.0
 */
class Plan_Service {

        use Singleton;

        /**
         * Signup service dependency.
         *
         * @since 2.5.0
         * @var Signup_Service
         */
        protected Signup_Service $signup_service;

        /**
         * Boot service dependencies.
         *
         * @since 2.5.0
         * @return void
         */
        public function init(): void {

                $this->signup_service = Signup_Service::get_instance();
        }

        /**
         * Retrieve the available plan products.
         *
         * @since 2.5.0
         *
         * @param array $query Optional query arguments.
         * @return array<int,Product>
         */
        public function get_plan_products(array $query = []): array {

                $query = wp_parse_args(
                        $query,
                        [
                                'active' => true,
                        ]
                );

                return $this->signup_service->get_plan_products($query);
        }

        /**
         * Return a normalized list of plan products ready for front-end consumption.
         *
         * @since 2.5.0
         *
         * @param array $query Optional query arguments.
         * @return array<int,array<string,mixed>>
         */
        public function get_normalized_plans(array $query = []): array {

                $products = $this->get_plan_products($query);

                $normalized = array_map([$this, 'get_normalized_plan'], $products);

                /**
                 * Filter the normalized plan collection generated by the plan service.
                 *
                 * @since 2.5.0
                 *
                 * @param array<int,array<string,mixed>> $normalized Normalized plan data.
                 * @param array<int,Product>             $products   Raw product objects.
                 * @param array                          $query      Query arguments.
                 * @param Plan_Service                    $service    Plan service instance.
                 */
                return apply_filters('wu_plan_service_normalized_plans', $normalized, $products, $query, $this);
        }

        /**
         * Normalize a product object into an associative array.
         *
         * @since 2.5.0
         *
         * @param Product $product Product instance to normalize.
         * @return array<string,mixed>
         */
        public function get_normalized_plan(Product $product): array {

                $normalized = [
                        'id'                       => (int) $product->get_id(),
                        'slug'                     => $product->get_slug(),
                        'name'                     => $product->get_name(),
                        'description'              => $product->get_description(),
                        'type'                     => $product->get_type(),
                        'currency'                 => $product->get_currency(),
                        'currency_symbol'          => wu_get_currency_symbol($product->get_currency()),
                        'pricing_type'             => $product->get_pricing_type(),
                        'amount'                   => (float) $product->get_amount(),
                        'formatted_amount'         => $product->get_formatted_amount(),
                        'initial_amount'           => (float) $product->get_initial_amount(),
                        'formatted_initial_amount' => wu_format_currency($product->get_initial_amount(), $product->get_currency()),
                        'setup_fee'                => (float) $product->get_setup_fee(),
                        'formatted_setup_fee'      => $product->has_setup_fee() ? wu_format_currency($product->get_setup_fee(), $product->get_currency()) : '',
                        'has_setup_fee'            => $product->has_setup_fee(),
                        'is_recurring'             => $product->is_recurring(),
                        'recurring_description'    => $product->get_recurring_description(),
                        'is_free'                  => $product->is_free(),
                        'duration'                 => (int) $product->get_duration(),
                        'duration_unit'            => $product->get_duration_unit(),
                        'billing_cycles'           => (int) $product->get_billing_cycles(),
                        'trial_duration'           => (int) $product->get_trial_duration(),
                        'trial_duration_unit'      => $product->get_trial_duration_unit(),
                        'has_trial'                => $product->get_trial_duration() > 0,
                        'feature_list'             => $this->sanitize_feature_list($product->get_feature_list()),
                        'price_variations'         => $this->normalize_price_variations($product),
                        'available_addons'         => $this->sanitize_id_list($product->get_available_addons()),
                        'is_taxable'               => $product->is_taxable(),
                        'tax_category'             => $product->get_tax_category(),
                        'group'                    => $product->get_group(),
                        'list_order'               => (int) $product->get_list_order(),
                        'shareable_url'            => $product->get_shareable_link(),
                        'contact_us_label'         => $product->get_contact_us_label(),
                        'contact_us_link'          => $product->get_contact_us_link(),
                        'onboarding_url'           => $product->get_onboarding_url(),
                        'onboarding_site_template' => $product->get_onboarding_site_template(),
                        'active'                   => $product->is_active(),
                ];

                /**
                 * Filter the normalized plan record generated by the plan service.
                 *
                 * @since 2.5.0
                 *
                 * @param array<string,mixed> $normalized Normalized plan data.
                 * @param Product             $product    Product instance.
                 * @param Plan_Service        $service    Plan service instance.
                 */
                return apply_filters('wu_plan_service_normalized_plan', $normalized, $product, $this);
        }

        /**
         * Resolve a plan product using either an id or slug.
         *
         * @since 2.5.0
         *
         * @param int|string $identifier Plan identifier.
         * @return Product|null
         */
        public function resolve_plan($identifier): ?Product {

                $product = null;

                if (is_numeric($identifier)) {
                        $product = Product::get_by_id((int) $identifier);
                } elseif (is_string($identifier) && $identifier !== '') {
                        $product = Product::get_by('slug', sanitize_title($identifier));
                }

                if ( ! $product instanceof Product) {
                        return null;
                }

                if ($product->get_type() !== Product_Type::PLAN) {
                        return null;
                }

                if ( ! $product->is_active()) {
                        return null;
                }

                return $product;
        }

        /**
         * Resolve the first matching plan product from a list of identifiers.
         *
         * @since 2.5.0
         *
         * @param array<int|string> $identifiers Product identifiers.
         * @return Product|null
         */
        public function resolve_plan_from_list(array $identifiers): ?Product {

                foreach ($identifiers as $identifier) {
                        $plan = $this->resolve_plan($identifier);

                        if ($plan) {
                                return $plan;
                        }
                }

                return null;
        }

        /**
         * Convert a list of raw feature strings into sanitized output.
         *
         * @since 2.5.0
         *
         * @param mixed $features Raw feature list.
         * @return array<int,string>
         */
        protected function sanitize_feature_list($features): array {

                if ( ! is_array($features)) {
                        return [];
                }

                $features = array_map('sanitize_text_field', $features);
                $features = array_filter($features, static fn($feature) => $feature !== '');

                return array_values($features);
        }

        /**
         * Normalize price variation data for a plan product.
         *
         * @since 2.5.0
         *
         * @param Product $product Product instance.
         * @return array<int,array<string,mixed>>
         */
        protected function normalize_price_variations(Product $product): array {

                $variations = [];

                foreach ($product->get_price_variations() as $variation) {
                        $duration      = absint($variation['duration'] ?? 0);
                        $duration_unit = $variation['duration_unit'] ?? $product->get_duration_unit();

                        $clone = clone $product;
                        $clone = $clone->get_as_variation($duration, $duration_unit);

                        if ( ! $clone instanceof Product) {
                                continue;
                        }

                        $variations[] = [
                                'duration'              => (int) $clone->get_duration(),
                                'duration_unit'         => $clone->get_duration_unit(),
                                'amount'                => (float) $clone->get_amount(),
                                'formatted_amount'      => $clone->get_formatted_amount(),
                                'recurring_description' => $clone->get_recurring_description(),
                        ];
                }

                return $variations;
        }

        /**
         * Sanitize a list of identifiers.
         *
         * @since 2.5.0
         *
         * @param mixed $list Raw identifiers.
         * @return array<int>
         */
        protected function sanitize_id_list($list): array {

                if (is_string($list)) {
                        $list = explode(',', $list);
                }

                if ( ! is_array($list)) {
                        return [];
                }

                $ids = array_map('absint', $list);
                $ids = array_filter($ids);

                return array_values(array_unique($ids));
        }
}
